# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python3\Bing Wallpaper Changer\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(717, 454)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ui/ot_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_preview = QtWidgets.QWidget()
        self.tab_preview.setObjectName("tab_preview")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_preview)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_image_preview = ImageLabel(self.tab_preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_image_preview.sizePolicy().hasHeightForWidth())
        self.lbl_image_preview.setSizePolicy(sizePolicy)
        self.lbl_image_preview.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_image_preview.setScaledContents(False)
        self.lbl_image_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_image_preview.setObjectName("lbl_image_preview")
        self.verticalLayout.addWidget(self.lbl_image_preview)
        self.lbl_image_info = QtWidgets.QLabel(self.tab_preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_image_info.sizePolicy().hasHeightForWidth())
        self.lbl_image_info.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_image_info.setFont(font)
        self.lbl_image_info.setWordWrap(True)
        self.lbl_image_info.setObjectName("lbl_image_info")
        self.verticalLayout.addWidget(self.lbl_image_info)
        self.lbl_image_date = QtWidgets.QLabel(self.tab_preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_image_date.sizePolicy().hasHeightForWidth())
        self.lbl_image_date.setSizePolicy(sizePolicy)
        self.lbl_image_date.setText("")
        self.lbl_image_date.setWordWrap(True)
        self.lbl_image_date.setObjectName("lbl_image_date")
        self.verticalLayout.addWidget(self.lbl_image_date)
        self.tabWidget.addTab(self.tab_preview, "")
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_settings)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.tab_settings)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.cb_resolution = QtWidgets.QComboBox(self.tab_settings)
        self.cb_resolution.setObjectName("cb_resolution")
        self.cb_resolution.addItem("")
        self.cb_resolution.addItem("")
        self.cb_resolution.addItem("")
        self.cb_resolution.addItem("")
        self.horizontalLayout_4.addWidget(self.cb_resolution)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.cb_auto_update = QtWidgets.QCheckBox(self.tab_settings)
        self.cb_auto_update.setChecked(True)
        self.cb_auto_update.setObjectName("cb_auto_update")
        self.verticalLayout_3.addWidget(self.cb_auto_update)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.tab_settings)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.sb_update_interval = QtWidgets.QSpinBox(self.tab_settings)
        self.sb_update_interval.setMinimum(1)
        self.sb_update_interval.setMaximum(1440)
        self.sb_update_interval.setProperty("value", 20)
        self.sb_update_interval.setObjectName("sb_update_interval")
        self.horizontalLayout_2.addWidget(self.sb_update_interval)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.cb_run_command = QtWidgets.QCheckBox(self.tab_settings)
        self.cb_run_command.setChecked(True)
        self.cb_run_command.setObjectName("cb_run_command")
        self.verticalLayout_3.addWidget(self.cb_run_command)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_2 = QtWidgets.QLabel(self.tab_settings)
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.le_command = QtWidgets.QLineEdit(self.tab_settings)
        self.le_command.setObjectName("le_command")
        self.horizontalLayout_3.addWidget(self.le_command)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem5)
        self.cb_enable_archive = QtWidgets.QCheckBox(self.tab_settings)
        self.cb_enable_archive.setChecked(True)
        self.cb_enable_archive.setObjectName("cb_enable_archive")
        self.verticalLayout_3.addWidget(self.cb_enable_archive)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem6 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.label_6 = QtWidgets.QLabel(self.tab_settings)
        self.label_6.setMinimumSize(QtCore.QSize(50, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.le_archive_location = QtWidgets.QLineEdit(self.tab_settings)
        self.le_archive_location.setObjectName("le_archive_location")
        self.horizontalLayout_6.addWidget(self.le_archive_location)
        self.button_archive_browse = QtWidgets.QPushButton(self.tab_settings)
        self.button_archive_browse.setObjectName("button_archive_browse")
        self.horizontalLayout_6.addWidget(self.button_archive_browse)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem7)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.tab_settings)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.rb_icon_colour_black = QtWidgets.QRadioButton(self.tab_settings)
        self.rb_icon_colour_black.setChecked(True)
        self.rb_icon_colour_black.setObjectName("rb_icon_colour_black")
        self.horizontalLayout_7.addWidget(self.rb_icon_colour_black)
        self.rb_icon_colour_white = QtWidgets.QRadioButton(self.tab_settings)
        self.rb_icon_colour_white.setObjectName("rb_icon_colour_white")
        self.horizontalLayout_7.addWidget(self.rb_icon_colour_white)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addLayout(self.verticalLayout_7)
        spacerItem10 = QtWidgets.QSpacerItem(20, 226, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem10)
        self.tabWidget.addTab(self.tab_settings, "")
        self.tab_desktop_environment = QtWidgets.QWidget()
        self.tab_desktop_environment.setObjectName("tab_desktop_environment")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_desktop_environment)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lbl_change_method = QtWidgets.QLabel(self.tab_desktop_environment)
        self.lbl_change_method.setObjectName("lbl_change_method")
        self.horizontalLayout_8.addWidget(self.lbl_change_method)
        spacerItem11 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.cb_change_method = QtWidgets.QComboBox(self.tab_desktop_environment)
        self.cb_change_method.setObjectName("cb_change_method")
        self.cb_change_method.addItem("")
        self.cb_change_method.addItem("")
        self.cb_change_method.addItem("")
        self.cb_change_method.addItem("")
        self.cb_change_method.addItem("")
        self.cb_change_method.addItem("")
        self.horizontalLayout_8.addWidget(self.cb_change_method)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        spacerItem12 = QtWidgets.QSpacerItem(20, 267, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem12)
        self.tabWidget.addTab(self.tab_desktop_environment, "")
        self.tab_history = QtWidgets.QWidget()
        self.tab_history.setObjectName("tab_history")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_history)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lw_wallpaper_history = ListWidget(self.tab_history)
        self.lw_wallpaper_history.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.lw_wallpaper_history.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.lw_wallpaper_history.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.lw_wallpaper_history.setMovement(QtWidgets.QListView.Static)
        self.lw_wallpaper_history.setResizeMode(QtWidgets.QListView.Adjust)
        self.lw_wallpaper_history.setViewMode(QtWidgets.QListView.IconMode)
        self.lw_wallpaper_history.setUniformItemSizes(True)
        self.lw_wallpaper_history.setObjectName("lw_wallpaper_history")
        self.verticalLayout_4.addWidget(self.lw_wallpaper_history)
        self.tabWidget.addTab(self.tab_history, "")
        self.tab_about = QtWidgets.QWidget()
        self.tab_about.setObjectName("tab_about")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_about)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.tab_about)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icons/ui/ot_icon.svg"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.tab_about)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.lbl_version = QtWidgets.QLabel(self.tab_about)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_version.setFont(font)
        self.lbl_version.setObjectName("lbl_version")
        self.verticalLayout_5.addWidget(self.lbl_version)
        self.label_7 = QtWidgets.QLabel(self.tab_about)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.label_8 = QtWidgets.QLabel(self.tab_about)
        self.label_8.setTextFormat(QtCore.Qt.RichText)
        self.label_8.setWordWrap(True)
        self.label_8.setOpenExternalLinks(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.tabWidget.addTab(self.tab_about, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_status = QtWidgets.QLabel(self.centralWidget)
        self.lbl_status.setObjectName("lbl_status")
        self.horizontalLayout.addWidget(self.lbl_status)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.button_refresh = QtWidgets.QPushButton(self.centralWidget)
        self.button_refresh.setObjectName("button_refresh")
        self.horizontalLayout.addWidget(self.button_refresh)
        self.button_close = QtWidgets.QPushButton(self.centralWidget)
        self.button_close.setObjectName("button_close")
        self.horizontalLayout.addWidget(self.button_close)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.actionDelete_Files = QtWidgets.QAction(MainWindow)
        self.actionDelete_Files.setObjectName("actionDelete_Files")
        self.label_3.setBuddy(self.cb_resolution)
        self.label.setBuddy(self.sb_update_interval)
        self.label_2.setBuddy(self.le_command)
        self.label_6.setBuddy(self.le_archive_location)
        self.lbl_change_method.setBuddy(self.cb_resolution)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.cb_resolution.setCurrentIndex(3)
        self.cb_change_method.setCurrentIndex(0)
        self.cb_auto_update.toggled['bool'].connect(self.sb_update_interval.setEnabled)
        self.cb_auto_update.toggled['bool'].connect(self.label.setEnabled)
        self.cb_run_command.toggled['bool'].connect(self.label_2.setEnabled)
        self.cb_run_command.toggled['bool'].connect(self.le_command.setEnabled)
        self.cb_enable_archive.toggled['bool'].connect(self.label_6.setEnabled)
        self.cb_enable_archive.toggled['bool'].connect(self.le_archive_location.setEnabled)
        self.cb_enable_archive.toggled['bool'].connect(self.button_archive_browse.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bing Wallpaper Changer"))
        self.lbl_image_preview.setText(_translate("MainWindow", "Loading..."))
        self.lbl_image_info.setText(_translate("MainWindow", "Loading..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_preview), _translate("MainWindow", "Preview"))
        self.label_3.setText(_translate("MainWindow", "Wallpaper resolution"))
        self.cb_resolution.setItemText(0, _translate("MainWindow", "1024x768"))
        self.cb_resolution.setItemText(1, _translate("MainWindow", "1280x720"))
        self.cb_resolution.setItemText(2, _translate("MainWindow", "1366x768"))
        self.cb_resolution.setItemText(3, _translate("MainWindow", "1920x1200"))
        self.cb_auto_update.setText(_translate("MainWindow", "Automatically update wallpaper"))
        self.label.setText(_translate("MainWindow", "Check for updates every:"))
        self.sb_update_interval.setSuffix(_translate("MainWindow", " minutes"))
        self.cb_run_command.setText(_translate("MainWindow", "Run command after changing wallpaper"))
        self.label_2.setText(_translate("MainWindow", "Command:"))
        self.cb_enable_archive.setText(_translate("MainWindow", "Keep a copy of images"))
        self.label_6.setText(_translate("MainWindow", "Location:"))
        self.button_archive_browse.setText(_translate("MainWindow", "Browse"))
        self.label_9.setText(_translate("MainWindow", "Icon colour"))
        self.rb_icon_colour_black.setText(_translate("MainWindow", "Black"))
        self.rb_icon_colour_white.setText(_translate("MainWindow", "White"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), _translate("MainWindow", "Settings"))
        self.lbl_change_method.setText(_translate("MainWindow", "Wallpaper change method"))
        self.cb_change_method.setItemText(0, _translate("MainWindow", "Unity"))
        self.cb_change_method.setItemText(1, _translate("MainWindow", "MATE"))
        self.cb_change_method.setItemText(2, _translate("MainWindow", "XFCE4"))
        self.cb_change_method.setItemText(3, _translate("MainWindow", "Feh"))
        self.cb_change_method.setItemText(4, _translate("MainWindow", "KDE4"))
        self.cb_change_method.setItemText(5, _translate("MainWindow", "Cinnamon"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_desktop_environment), _translate("MainWindow", "Desktop Environment"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_history), _translate("MainWindow", "History"))
        self.label_5.setText(_translate("MainWindow", "Bing Wallpaper Changer"))
        self.lbl_version.setText(_translate("MainWindow", "Version %"))
        self.label_7.setText(_translate("MainWindow", "Copyright © 2019 Gary Hughes, overThere.co.uk"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>This program is released under the GPL v3 and all source can be downloaded from:</p><p><a href=\"https://bitbucket.org/gary_hughes/bing-wallpaper-changer\"><span style=\" text-decoration: underline; color:#0000ff;\">https://bitbucket.org/gary_hughes/bing-wallpaper-changer</span></a></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_about), _translate("MainWindow", "About"))
        self.lbl_status.setText(_translate("MainWindow", "CURRENT STATUS"))
        self.button_refresh.setText(_translate("MainWindow", "Refresh"))
        self.button_close.setText(_translate("MainWindow", "Close"))
        self.actionDelete_Files.setText(_translate("MainWindow", "Delete Files"))


from ui.custom_widgets import ImageLabel, ListWidget
from . import rec_rc
